In [4]:
a = 'cobre'
b = 'cafe'

In [6]:
print (a)

cobre


In [8]:
print (b)

cafe


In [11]:
x = 'Los productos tradicionales mas exportados son '

In [13]:
print (x)

Los productos tradicionales mas exportados son: 


In [38]:
print(f'{x} {a} y {b}')

Los productos tradicionales con mayor volumen de exportación fueron: cobre y cafe cobre y cafe


In [27]:
d = 'Huancayo'
e = 'Lima'
f = 'Tacna'

In [35]:
y = 'El paro de transportistas han generado revueltas en'
print (y)

El paro de transportistas han generado revueltas en:


In [39]:
print(f'{y} {d}, {e} y {f}')

El paro de transportistas han generado revueltas en: Huancayo, Junin y Tacna


In [83]:
L1 = ['San Miguel', 'Jesus Maria', 'Lince']
print (L1)

['San Miguel', 'Jesus Maria', 'Lince']


In [84]:
L1.append ('La Perla')
print (L1)

['San Miguel', 'Jesus Maria', 'Lince', 'La Perla']


In [85]:
L1.append ('Bellavista')
print (L1)

['San Miguel', 'Jesus Maria', 'Lince', 'La Perla', 'Bellavista']


In [91]:
L1[0]

'San Miguel'

In [93]:
L1[4]

'Bellavista'

In [137]:
Distritos_pob = {'San Miguel': {'Poblacion':173309, 'Pobreza': 2.2}, 
                 'Jesus Maria':{'Poblacion':81743, 'Pobreza': 0.8}, 
                 'Lince': {'Poblacion':59578, 'Pobreza': 2.2}, 
                 'La Perla': {'Poblacion':64454, 'Pobreza':4.1}, 
                 'Bellavista': {'Poblacion':80704, 'Pobreza': 6.2}}


In [125]:
Distritos_pob.get('Jesus Maria').get('Poblacion')

81743

In [126]:
Distritos_pob.get('Jesus Maria').get('Pobreza')

0.8

In [131]:
Distritos_pob.get('La Perla').get('Poblacion')

64454

In [133]:
Distritos_pob.get('La Perla').get('Pobreza')

4.1

In [135]:
Distritos_pob.get('Lince').get('Poblacion')

59578

In [138]:
Distritos_pob.get('Lince').get('Pobreza')

2.2

In [4]:
import numpy as np

In [146]:
m=np.array([[0,1,2],[5,6,7]])
print(m)

[[0 1 2]
 [5 6 7]]


In [150]:
n=np.array([[5,1,7],[8,9,10]])
print(n)

[[ 5  1  7]
 [ 8  9 10]]


In [154]:
con1 = np.concatenate((m,n), axis = 0)
print (con1)

[[ 0  1  2]
 [ 5  6  7]
 [ 5  1  7]
 [ 8  9 10]]


In [156]:
con2 = np.concatenate((m,n), axis = 1)
print (con2)

[[ 0  1  2  5  1  7]
 [ 5  6  7  8  9 10]]


In [158]:
mat=np.array([[0,1,2,3,4,5,6,7],[8,9,10,11,12,13,14,15],[16,17,18,19,20,21,22,23],[24,25,26,27,28,29,30,31]])
print(mat)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]


In [166]:
mat[:,6:8] #2 ultimas columna

array([[ 6,  7],
       [14, 15],
       [22, 23],
       [30, 31]])

In [167]:
mat[0:3,:] #3 primeras filas

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [81]:
import random 

random.seed(20)
x1 = np.random.rand(15) # uniform distribution  [0,1]
x2 = np.random.rand(15) # uniform distribution [0,1]
x3 = np.random.rand(15) # uniform distribution [0,1]
e = np.random.normal(0,1,15) # normal distribution mean = 0 and sd = 1
# Poblacional regression (Data Generating Process GDP)


Y = 12 + 3*x1 + 5*x2 + 1*x3 + e

In [82]:
X = np.column_stack((np.ones(15),x1,x2,x3))
print(X)

[[1.         0.37254688 0.10518088 0.41913548]
 [1.         0.87342802 0.36360532 0.774164  ]
 [1.         0.80459394 0.27849757 0.34844235]
 [1.         0.81084845 0.30702409 0.51588666]
 [1.         0.96509327 0.04305801 0.21010921]
 [1.         0.54706281 0.89064658 0.75647955]
 [1.         0.24181599 0.17270884 0.19066395]
 [1.         0.40206489 0.23073873 0.21692932]
 [1.         0.79173805 0.0515791  0.25101049]
 [1.         0.54902013 0.69023937 0.9081091 ]
 [1.         0.80511501 0.43915097 0.18866016]
 [1.         0.29618197 0.37011467 0.89137945]
 [1.         0.28455421 0.12308594 0.77627387]
 [1.         0.45355846 0.44378246 0.39099901]
 [1.         0.21555325 0.56460776 0.3862849 ]]


In [55]:
coef= np.array([[3,0,0],
       [0,5,0],
       [0,0,1]])
coef

array([[3, 0, 0],
       [0, 5, 0],
       [0, 0, 1]])

In [58]:
np.cov(coef) #matriz de covarianzas

array([[ 3.        , -2.5       , -0.5       ],
       [-2.5       ,  8.33333333, -0.83333333],
       [-0.5       , -0.83333333,  0.33333333]])

In [89]:
from sklearn.model_selection import train_test_split 
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

In [90]:
from sklearn.linear_model import LinearRegression
modelo = LinearRegression().fit(X_train,Y_train)
Y_predict = modelo.predict(X_test) 
modelo.score(X_test,Y_predict)

1.0

In [91]:
modelo.coef_

array([0.        , 2.59145301, 2.149207  , 1.69987081])

In [93]:
modelo.intercept_

13.109132201571361

In [95]:
print (Y_predict)

[17.55902752 16.1873568  15.0131016  15.90293581 17.72692114]


In [101]:
n = len(Y)
print (n)

15


In [118]:
k=5
k

5

In [116]:
from sklearn.metrics import mean_squared_error
y_true  = Y_test
y_pred  = Y_predict
mean_squared_error(y_true,y_pred)

1.0648750843754289

In [119]:
sumatoria = mean_squared_error(y_true,y_pred)*n
sumatoria

15.973126265631434

In [122]:
a = n - k 
a

10

In [125]:
estimador = sumatoria/a
estimador

1.5973126265631434

In [148]:
I = np.eye(15)
print(I)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [146]:
Xinversa = X @ (np.linalg.inv(X.T @ X) )@ X.T
Xinversa

array([[ 0.18761507, -0.00084016,  0.02395567,  0.02075663,  0.06072518,
        -0.10657388,  0.18391847,  0.12788883,  0.10018881, -0.0309171 ,
        -0.03901995,  0.13716274,  0.21916504,  0.05109766,  0.06487697],
       [-0.00084016,  0.3110993 ,  0.1154724 ,  0.18487359,  0.15449887,
         0.09790063, -0.15940512, -0.09308962,  0.10185666,  0.19200267,
         0.02464473,  0.13091862,  0.11320005, -0.0296232 , -0.14350943],
       [ 0.02395567,  0.1154724 ,  0.13804475,  0.12403119,  0.18757953,
         0.04364015,  0.01450234,  0.05177207,  0.14151737,  0.02742842,
         0.1551737 , -0.03636171, -0.03114722,  0.05030013, -0.00590881],
       [ 0.02075663,  0.18487359,  0.12403119,  0.14241138,  0.16786394,
         0.06019279, -0.04490871, -0.00049413,  0.12318229,  0.08917053,
         0.09720741,  0.03530754,  0.03405933,  0.0203992 , -0.05405298],
       [ 0.06072518,  0.15449887,  0.18757953,  0.16786394,  0.32289902,
        -0.10711199,  0.01285408,  0.05694475, 

In [151]:
Matriz = I - Xinversa
Matriz

array([[ 8.12384927e-01,  8.40158665e-04, -2.39556745e-02,
        -2.07566341e-02, -6.07251843e-02,  1.06573876e-01,
        -1.83918470e-01, -1.27888828e-01, -1.00188809e-01,
         3.09170966e-02,  3.90199539e-02, -1.37162742e-01,
        -2.19165036e-01, -5.10976648e-02, -6.48769680e-02],
       [ 8.40158665e-04,  6.88900702e-01, -1.15472400e-01,
        -1.84873589e-01, -1.54498873e-01, -9.79006302e-02,
         1.59405123e-01,  9.30896165e-02, -1.01856662e-01,
        -1.92002674e-01, -2.46447276e-02, -1.30918617e-01,
        -1.13200050e-01,  2.96231977e-02,  1.43509427e-01],
       [-2.39556745e-02, -1.15472400e-01,  8.61955248e-01,
        -1.24031193e-01, -1.87579534e-01, -4.36401546e-02,
        -1.45023434e-02, -5.17720700e-02, -1.41517373e-01,
        -2.74284208e-02, -1.55173695e-01,  3.63617139e-02,
         3.11472197e-02, -5.03001330e-02,  5.90881083e-03],
       [-2.07566341e-02, -1.84873589e-01, -1.24031193e-01,
         8.57588615e-01, -1.67863939e-01, -6.01927917